# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  A blog mainly about Anime, Film, Music, TV and programming in Ruby, JavaScript, C++ and Scala.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.chilon.net" # the base hostname & protocol for your site
twitter_username: ChilonDotNet
github_username:  ohjames

# Build settings
markdown: kramdown
