# Site settings
title: chilon.net blog
description: > # this means to ignore newlines until "baseurl:"
  A blog about the technical exploits of chilon.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.chilon.net" # the base hostname & protocol for your site
twitter_username: ChilonDotNet
github_username:  ohjames

# Build settings
markdown: kramdown
